version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "skip-changelog"
  - package-ecosystem: "cargo"
    directory: "/blinkenbox"
    schedule:
      interval: "daily"
