name: "CI"
on:
  pull_request:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  formatcheck:
    name: cargo fmt
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - run: cargo fmt --check
        working-directory: blinkenbox

  clippycheck:
    name: cargo clippy
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - run: cargo clippy --release
        working-directory: blinkenbox

  build:
    name: build firmware
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: riscv32imc-unknown-none-elf
      - run: cargo build --release
        working-directory: blinkenbox
